POST  http://kit/api/auth/login HTTP/1.1
content-type: application/json

{
    "username":"Иван",
    "password":"123"
}

###
GET  http://kit/api/products HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Ilx1MDQxOFx1MDQzMlx1MDQzMFx1MDQzZCIsImlhdCI6MTY5NTI5NjQwMSwiZXhwIjoxNjk1MzgyODAxfQ.A6X2nqpGESSmhffNFLLVQifSyzVv8qIaadtl0wnXlaI
